CATALOGUE_HOST: catalogue.backend-{{ env }}.devops84.shop
USER_HOST: user.backend-{{ env }}.devops84.shop
CART_HOST: cart.backend-{{ env }}.devops84.shop
SHIPPING_HOST: shipping.backend-{{ env }}.devops84.shop
PAYMENT_HOST: payment.backend-{{ env }}.devops84.shop