- name: app setup
  include_role:
    name: common
    tasks_from: app-setup  # include common tasks for application setup

- name: python setup
  include_role:
    name: common
    tasks_from: python

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd