- name: app setup 
  include_role:
    name: common
    tasks_from: app-setup

- name: Disable the default nodejs module
  ansible.builtin.command: dnf module disable nginx -y

- name: enable nginx
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes   #working good upto 21 line

- name: remove htm directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
  
- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download frontend code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: unzip frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: remove default nginx config
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: copy roboshop nginx conf
  ansible.builtin.template:
    src: nginx.conf.j2
    # this is a Jinja2 template file for the nginx configuration
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart nginx

