- name: install python3 packages
  ansible.builtin.dnf:
    name: "{{ item }}"  # install python3, gcc, and python3-devel packages
    state: installed
  loop:
    - python3
    - gcc
    - python3-devel

- name: install dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app  # change directory to /app before running the comman 